#!/bin/bash
#SBATCH --account=def-hpcg1725
#SBATCH --partition=reserved
#SBATCH --qos=privileged
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --job-name=mtp train
#SBATCH --output=./mtpProperties/out.run
#SBATCH --time=00-00:10 # time (DD-HH:MM)
#SBATCH --wait

module load    StdEnv/2020  gcc/9.3.0  openmpi/4.0.3

mpirun -np 1 /global/home/hpc5146/mlip-2/bin/mlp train /global/home/hpc5146/Projects/K-MTP-training/phase3/mtpProperties/pot.mtp /global/home/hpc5146/Projects/K-MTP-training/phase3/mtpProperties/train.cfg --energy-weight=1 --force-weight=0.01 --stress-weight=0.001 --max-iter=10000 --bfgs-conv-tol=0.000001 --trained-pot-name=/global/home/hpc5146/Projects/K-MTP-training/phase3/mtpProperties/pot.mtp