#!/bin/bash
#SBATCH --account=$account
#SBATCH --partition=$partition
#SBATCH --qos=$qos
#SBATCH --nodes=1
#SBATCH --cpus-per-task=4
#SBATCH --job-name=train
#SBATCH --output=$outfile
#SBATCH --time=00-02:00 # time (DD-HH:MM)
#SBATCH --mem-per-cpu=8G
#SBATCH --wait

module load       StdEnv/2020  gcc/9.3.0  cuda/11.2.2
module load openmpi/4.0.3

mpirun -np 4 --oversubscribe $mlp train $mtp $train --iteration_limit=10000 --tolerance=0.000001