#!/bin/bash
#SBATCH --account=def-hpcg1725
#SBATCH --partition=reserved
#SBATCH --qos=privileged
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --job-name=TrainMTP
#SBATCH --output=./create.out
#SBATCH --mem-per-cpu=8G
#SBATCH --time=0-010:00 # time (DD-HH:MM)
#SBATCH --mail-type=FAIL
#SBATCH --mail-user=17zjm1@queensu.ca
#SBATCH

source  ../ENV/bin/activate
python createTrainedPotential.py