#!/bin/bash
#SBATCH --account=def-hpcg1725
#SBATCH --partition=reserved
#SBATCH --qos=privileged
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=24
#SBATCH --job-name=mdrun
#SBATCH --output=out.run
#SBATCH --mem-per-cpu=16G
#SBATCH --time=0-02:00 # time (DD-HH:MM)


module load       StdEnv/2020  gcc/9.3.0  cuda/11.2.2
module load openmpi/4.0.3

mpirun -np 24 --oversubscribe /global/home/hpc5146/interface-lammps-mlip-2/lmp_mpi  < in.run > out.run
