units            metal
dimension        3
boundary         p p p

# read data
atom_style       atomic
lattice          bcc 5.11
region           whole block 0 20 0 20 0 20 units lattice
create_box       1  whole
create_atoms     1 region whole
mass             1 39.0983


# potential

#pair_style hybrid/overlay zbl 0.8 1 mlip mlip.ini
#pair_coeff * * zbl 11 11
#pair_coeff  * * mlip

pair_style mlip mlip.ini
pair_coeff * *

#------------------Parameters
thermo                  1000
timestep         0.001
neighbor 2.0 bin
neigh_modify every 1 delay 5 check yes

#outputs
thermo           10
thermo_style     custom step temp pe press vol lx ly lz density

dump            2 all custom 1000 md.*.traj id type x y z

velocity all create 1.0 4928459 rot yes dist gaussian
fix             1 all npt temp 1 1 0.1 aniso 0 0 1
run             500
unfix           1


fix             1 all npt temp 400 400 0.1 aniso 0 0 1
run             900000
unfix           1

