#!/bin/bash
#SBATCH --account=$account
#SBATCH --partition=$partition
#SBATCH --qos=$qos
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --job-name=calcGrade
#SBATCH --output=$outfile
#SBATCH --time=00-00:10 # time (DD-HH:MM)
#SBATCH --mem-per-cpu=8G
#SBATCH --wait

module load    StdEnv/2020  gcc/9.3.0  openmpi/4.0.3

mpirun -np 1 $mlp  calc-grade $mtp $train $train $outconfigs --als-filename=$als
